namespace CarSpace.Services.Core.Contracts.CarShop.CarShopListing.Responses;

public record GetCarShopListingByIdResponse(
    Guid Id,
    string Title,
    string Description,
    int BrandId,
    string BrandName,
    string Model,
    int Year,
    int Mileage,
    int Horsepower,
    string Transmission,
    string FuelType,
    string Color,
    string EuroStandard,
    int Doors,
    decimal Price,
    string City,
    string Address,
    string ImageUrl,
    bool IsSavedByCurrentUser,
    DateTime UpdatedAt,
    Guid UserId,
    string UserNickname);
