// <auto-generated />
using System;
using CarSpace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarSpace.Data.Migrations
{
    [DbContext(typeof(CarSpaceDbContext))]
    [Migration("20250731084157_SeedingCarServiceCategories")]
    partial class SeedingCarServiceCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarSpace.Data.Models.CarForum.CarForumArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.HasIndex("UserId");

                    b.ToTable("CarForumArticles");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarForum.CarForumBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CarForumBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mercedes"
                        });
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarForum.CarForumComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarForumArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarForumArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("CarForumArticleComments");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarForum.UserSavedCarForumArticle", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarForumArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CarForumArticleId");

                    b.HasIndex("CarForumArticleId");

                    b.ToTable("UserSavedCarForumArticles");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarServices.CarServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CarServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Repair"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Washing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Detailing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tire Services"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Oil Change"
                        });
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarServices.CarServiceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("CarServiceListings");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarServices.UserSavedCarService", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarServiceListingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CarServiceListingId");

                    b.HasIndex("CarServiceListingId");

                    b.ToTable("UserSavedCarServices");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarShop.CarCarsAndSuvsListingBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CarCarsAndSuvsListingBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mercedes"
                        });
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarShop.CarsAndSuvsListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<string>("EuroStandard")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.HasIndex("UserId");

                    b.ToTable("CarsAndSuvsListings");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarShop.UserSavedCarsAndSuvsListing", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarsAndSuvsListingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CarsAndSuvsListingId");

                    b.HasIndex("CarsAndSuvsListingId");

                    b.ToTable("UserSavedCarsAndSuvsListings");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.Meet.CarMeet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("MeetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CarMeets");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.Meet.UserCarMeetParticipant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarMeetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CarMeetId");

                    b.HasIndex("CarMeetId");

                    b.ToTable("UserCarMeetParticipants");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.Meet.UserSavedCarMeet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarMeetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CarMeetId");

                    b.HasIndex("CarMeetId");

                    b.ToTable("UserSavedCarMeets");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.User.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarSpace.Data.Models.CarForum.CarForumArticle", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.CarForum.CarForumBrand", "CarBrand")
                        .WithMany("CarForumArticles")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("CreatedCarForumArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarForum.CarForumComment", b =>
                {
                    b.HasOne("CarSpace.Data.Models.CarForum.CarForumArticle", "CarForumArticle")
                        .WithMany("Comments")
                        .HasForeignKey("CarForumArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("CreatedCarForumComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarForumArticle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarForum.UserSavedCarForumArticle", b =>
                {
                    b.HasOne("CarSpace.Data.Models.CarForum.CarForumArticle", "CarForumArticle")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("CarForumArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("SavedCarForumArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarForumArticle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarServices.CarServiceListing", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.CarServices.CarServiceCategory", "Category")
                        .WithMany("CarServiceListings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("CreatedCarServiceListings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarServices.UserSavedCarService", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.CarServices.CarServiceListing", "CarServiceListing")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("CarServiceListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("SavedServiceListings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarServiceListing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarShop.CarsAndSuvsListing", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.CarShop.CarCarsAndSuvsListingBrand", "Brand")
                        .WithMany("Listings")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("CreatedCarsAndSuvsListings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarShop.UserSavedCarsAndSuvsListing", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.CarShop.CarsAndSuvsListing", "Listing")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("CarsAndSuvsListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("SavedCarsAndSuvsListings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.Meet.CarMeet", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("CreatedCarMeets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.Meet.UserCarMeetParticipant", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.Meet.CarMeet", "CarMeet")
                        .WithMany("Participants")
                        .HasForeignKey("CarMeetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("JoinedCarMeets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarMeet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.Meet.UserSavedCarMeet", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.Meet.CarMeet", "CarMeet")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("CarMeetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", "User")
                        .WithMany("SavedCarMeets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarMeet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CarSpace.Data.Models.Entities.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarSpace.Data.Models.CarForum.CarForumArticle", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarForum.CarForumBrand", b =>
                {
                    b.Navigation("CarForumArticles");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarServices.CarServiceCategory", b =>
                {
                    b.Navigation("CarServiceListings");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarServices.CarServiceListing", b =>
                {
                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarShop.CarCarsAndSuvsListingBrand", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.CarShop.CarsAndSuvsListing", b =>
                {
                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.Meet.CarMeet", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("CarSpace.Data.Models.Entities.User.ApplicationUser", b =>
                {
                    b.Navigation("CreatedCarForumArticles");

                    b.Navigation("CreatedCarForumComments");

                    b.Navigation("CreatedCarMeets");

                    b.Navigation("CreatedCarServiceListings");

                    b.Navigation("CreatedCarsAndSuvsListings");

                    b.Navigation("JoinedCarMeets");

                    b.Navigation("SavedCarForumArticles");

                    b.Navigation("SavedCarMeets");

                    b.Navigation("SavedCarsAndSuvsListings");

                    b.Navigation("SavedServiceListings");
                });
#pragma warning restore 612, 618
        }
    }
}
